frr version 9.1
frr defaults traditional
hostname fw-int
log syslog informational
no ipv6 forwarding
!
interface eth1
 ip address 10.0.10.254/24
!
interface eth2
 ip address 10.0.20.1/24
!
ip forwarding
ip route 0.0.0.0/0 10.0.10.1
!
line vty
!
